apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-kafka-consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ${ECR_REGISTRY}/shadowmess-consumer:${IMAGE_TAG}
        command: ["python", "-m", "services.flink_jobs.consumer"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: kafka-brokers
